/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    `maven-publish`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "peak.ais.service.discovery"
            artifactId = "library"
            version = "0.0.1"

            from(components["java"])
        }
    }
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:28.2-jre")
    implementation(platform("com.amazonaws:aws-java-sdk-bom:1.11.774"))
    implementation("com.amazonaws:aws-java-sdk-dynamodb")
    implementation("com.amazonaws:aws-java-sdk-sqs")
    implementation("com.amazonaws:aws-java-sdk-sns")
    implementation("com.amazonaws:aws-java-sdk-sts")
    implementation("com.amazonaws:aws-java-sdk-lambda")
    implementation("com.amazonaws:aws-java-sdk-servicediscovery")
    implementation("org.jetbrains:annotations:20.1.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.8.9")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}
